apiVersion: v1
kind: Service
metadata:
  name: {{ template "pg-stats.fullname" . }}
  labels:
    app: {{ template "pg-stats.name" . }}
    chart: {{ template "pg-stats.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9187
      protocol: TCP
      targetPort: 9187
  selector:
    app: {{ template "pg-stats.name" . }}
    release: {{ .Release.Name }}
